myapp/files/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, FileField
from wtforms.validators import DataRequired, Length, EqualTo, ValidationError
from flask_ckeditor import CKEditorField
from flask_wtf.file import FileField, FileAllowed
from flask import request
from myapp.models import Genre
from wtforms.ext.sqlalchemy.fields import QuerySelectField

def choice_query():
    return Genre.query


class FileForm(FlaskForm):
    title=StringField('Title/Titre', validators=[DataRequired(), Length(min=2, max=40)])
    auteur=StringField('Author/Auteur', validators=[DataRequired(), Length(min=0, max=100)])
    description=TextAreaField('About the doc', validators=[DataRequired(), Length(10, 500)])
    filedata = FileField('Upload the doc', validators=[FileAllowed(['pdf', 'epub'])])
    cover=FileField('Upload doc cover', validators=[FileAllowed(['jpg', 'png', 'jpeg'])])
    genre=QuerySelectField('Genre', query_factory=choice_query, allow_blank=True, get_label='title', validators=[DataRequired()])
    submit=SubmitField('Add/Ajouter')
    

class EbookForm(FlaskForm):
    title=StringField('Title / Titre', validators=[DataRequired(), Length(min=2, max=40)])  
    author=StringField('Author / Auteur', validators=[DataRequired(), Length(min=2, max=40)])
    submit=SubmitField('Command/Commander')  


class SearchForm(FlaskForm):
    search = StringField('', validators=[DataRequired()])
    submit=SubmitField('Search/Rechercher')

myapp/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, FileField 
from wtforms.validators import DataRequired, Length, EqualTo, ValidationError
from flask_ckeditor import CKEditorField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from myapp.models import Genre


def choice_query():
    return Genre.query


class PostForm(FlaskForm):
    title=StringField('Title/Titre', validators=[DataRequired(), Length(min=5, max=150)])
    genre=QuerySelectField('Genre', query_factory=choice_query, allow_blank=True, get_label='title', validators=[DataRequired()])
    submit=SubmitField('Continuer')
    
class TagForm(FlaskForm):
    title=StringField('', validators=[DataRequired(), Length(min=2, max=80)]) 
    submit=SubmitField('validate')   

myapp/files/routes.py
from flask import (render_template, url_for, flash, make_response,
                   redirect, request, abort, Blueprint, request, send_file, Response, g, current_app)
from flask_login import current_user, login_required
from myapp.factory import db, mail
from myapp.models import File, Ebook, Cover, User, Notif, Genre
from myapp.files.forms import FileForm, EbookForm, SearchForm
from myapp.users.utils import save_picture, send_reset_email, send_mail, msg_to_dict
import bleach
from io import BytesIO
from flask import Markup
from flask_mail import Message
from sqlalchemy.orm.util import join
from datetime import datetime
import os



files=Blueprint('files', __name__)


ALLOWED_EXTENSIONS=set(['pdf', 'epub'])
EXTENSIONS_ALLOWED=set(['jpeg', 'png', 'jpg'])

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def file_allowed(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in EXTENSIONS_ALLOWED


@login_required
@files.route("/files", methods=['GET', 'POST'])
def allfiles():
    page = request.args.get('page', 1, type=int)
    files = File.query.order_by(File.date_posted.desc()).paginate(page=page, per_page=12)
    genres=Genre.query.all()
    return render_template('files.html', files=files, genres=genres)


@files.route('/img/<int:img_id>', methods=['GET', 'POST'])
def serve_image(img_id):
    image=Cover.query.get_or_404(img_id)
    return image.data



@login_required
@files.route('/home/upload', methods=['GET', 'POST'])
def upload():
    form=FileForm()      
    #if form.is_submitted():
        
    if form.validate_on_submit():
        flash('Your file has been successfully uploaded !', 'succes')        
        form.filedata.data.seek(0, os.SEEK_END)
        file_length=form.filedata.data.tell()/1000000
        file_length=str(file_length)[:4]
        category=form.genre.data
        newFile=File(title=form.title.data.title(), data=form.filedata.data.read(), 
            description=form.description.data, uploader=current_user, downloaded=0,
            file_size=file_length, category=category.title, auteur=form.auteur.data)
        cover=Cover(file=newFile, data=form.cover.data.read())
        flash('Your file has been successfully uploaded', 'success')
        db.session.add(cover)            
        db.session.commit()  
        newFile.img_id=cover.id
        db.session.add(newFile)
        db.session.commit()
              
    return render_template("fileupload.html", form=form)



@login_required
@files.route('/home/upload/<int:recommender_id>/<int:ebook_id>', methods=['GET', 'POST'])
def uploadv(recommender_id, ebook_id):
    form=FileForm()
    recommender=User.query.filter_by(id=recommender_id).first()
    ebook=Ebook.query.filter_by(id=ebook_id).first()
    flash('Keep making the library grow for the sake of all', 'success')
    if form.validate_on_submit():
               
        form.filedata.data.seek(0, os.SEEK_END)
        file_length=form.filedata.data.tell()/1000000
        file_length=str(file_length)[:4]
        category=form.genre.data
        newFile=File(title=ebook.title.title(), data=form.filedata.data.read(), 
            description=form.description.data, uploader=current_user, downloaded=0,
            file_size=file_length, category=category.title, auteur=form.auteur.data)
        cover=Cover(file=newFile, data=form.cover.data.read())
        flash('Your file has been successfully uploaded. Thank you very much !', 'success')
        db.session.add(cover)            
        db.session.commit()  
        newFile.img_id=cover.id
        db.session.add(newFile)
        db.session.commit()
    
        send_mail(recommender.email,'Recommended Ebook uploaded', 'ebookuploaded', username=recommender.username, title=newFile.title)
        return redirect(url_for('files.allfiles')) 
              
    return render_template("fileupload2.html", form=form, title=ebook.title.capitalize())


@login_required
@files.route("/file/<int:file_id>", methods=['GET', 'POST'])
def file(file_id):
    
    file = File.query.get_or_404(file_id)
    return render_template('file.html', title=file.title, file=file, file_id=file_id, cover=file.cover, file_size=file.file_size, img_id=file.img_id)

@login_required
@files.route('/file/<int:file_id>/download', methods=['POST', 'GET'])
def download(file_id):
    file_data=File.query.get_or_404(file_id)
    file_data.downloads()
    db.session.commit()
    return send_file(BytesIO(file_data.data), attachment_filename=file_data.title, as_attachment=True) 



@login_required
@files.route("/home/recommend", methods=['GET', 'POST'])
def recommend():
    form=EbookForm()
    if form.validate_on_submit():
        flash("Your recommendation is received, we'll reply soon", 'success')
        ebook=Ebook(title=form.title.data.capitalize(), author=form.author.data, recommender=current_user)
        db.session.add(ebook)
        db.session.commit()
        send_mail(current_user.email,'Recommendation of an Ebook', 'ebookrecommendation', username=current_user.username, title=ebook.title)
        return redirect(url_for('main.home'))  
    return render_template('recommend.html', form=form)


@login_required
@files.route('/home/ebooks', methods=['GET'])    
def ebooks():
    page = request.args.get('page', 1, type=int)
    ebooks = Ebook.query.order_by(Ebook.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('Ebooks.html', ebooks=ebooks)


@files.route('/home/files/<string:category>')
def files_bygenre(category):
    form=SearchForm()
    page = request.args.get('page', 1, type=int)
    genre=Genre.query.filter_by(title=category).first()
    genres=Genre.query.all()
    files=File.query.filter_by(category=genre.title)\
        .order_by(File.date_posted.desc())\
        .paginate(page=page, per_page=6)
    return render_template('files_bygenre.html', files=files, genre=genre, form=form, genres=genres)

myapp/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from myapp.factory import db
from myapp.models import Post, Comment, Tag, Reply, Genre, Notif
from myapp.posts.forms import PostForm, TagForm
from myapp.comments.forms import CommentForm
import bleach
from flask import Markup
from flask import send_from_directory
from myapp.files.forms import SearchForm

posts=Blueprint('posts', __name__)


@posts.route("/post/newpost", methods=['GET', 'POST'])
@login_required
def new_post():
    if not current_user.is_publisher():
        flash('If you want to make post, fisrtly contact the EkoB team. thank you', 'success')
        return redirect(url_for('main.home'))
    form=PostForm()
    if form.validate_on_submit():
        title=form.title.data
        title=title.capitalize()
        genre=form.genre.data
        
        flash('Your Post need a content!', 'succes')
        return redirect(url_for('posts.Newpost', title=title, category=genre.title))   
    return render_template('create_post.html', form=form, title='New Post', legend='New post')


@posts.route("/post/newpost/<string:title>/<string:category>", methods=['GET', 'POST'])
@login_required
def Newpost(title, category):
    if not current_user.is_publisher():
        flash('You have to contact the admin for access', 'danger')
        return redirect(url_for('main.home'))
    tags=Tag.query.all()
    
    if request.method=='POST':
        content=request.form.get('postcontent')
        if content=="":
            flash('The post must have a content', 'danger')
            return redirect(url_for('main.home'))
        else:    
            post=Post(title=title.title(), content=content, author=current_user, category=category)
              
            db.session.add(post)
            db.session.commit()
           
            flash('Your post has been created and saved ! But you have to select some tags please', 'succes')    
            return redirect(url_for('posts.tagin', post_id=post.id))
    return render_template('new_post.html', title='New Post', tags=tags)


@posts.route("/post/newpost/<int:post_id>/tagsinput", methods=['GET', 'POST'])
@login_required
def tagin(post_id):
    form=TagForm()
    tags=Tag.query.all()
    post=Post.query.get_or_404(post_id)
    if form.validate_on_submit():
        flash('Thank you very much '+current_user.username+' !', 'success')
        titles=form.title.data
        return redirect(url_for('posts.tagpicked', post_id=post.id, titles=titles))
    return render_template('tagsinput.html', form=form, tags=tags, post=post)


@posts.route("/post/newpost/<int:post_id>/tagsinput/<string:titles>", methods=['GET', 'POST'])
@login_required
def tagpicked(post_id, titles):
    post=Post.query.get_or_404(post_id)
    titles=titles.split()
    for title in titles:
        title=title.capitalize()
        if Tag.query.filter_by(title=title).count()==1:
            tag=Tag.query.filter_by(title=title).first()
            post.tags.append(tag)
            db.session.commit()
    
    return redirect(url_for('main.home'))


@posts.route("/post/newpost/<int:post_id>/tagsinput/<int:tag_id>", methods=['GET', 'POST'])
@login_required
def tagpick(post_id, tag_id):
    post=Post.query.get_or_404(post_id)
    tag=Tag.query.get_or_404(tag_id)
    post.tags.append(tag)
    db.session.commit()
    return redirect(url_for('posts.tagin', post_id=post.id))


@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
def post(post_id):
    
    post = Post.query.get_or_404(post_id)
    post.read+=1
    db.session.commit()
    comments= Comment.query.filter_by(post_id=post_id)\
        .order_by(Comment.date_posted.desc())\
        .all()
    rposts=Post.query.filter(Post.id != post.id ).filter_by(category=post.category).limit(5).all()
    if request.method=="POST":
        content=request.form.get('comment')
        
        if len(content) > 0:
            return commenter(content, post.id) 

    return render_template('post.html', title=post.title, post=post, rposts=rposts, comments=comments)
                                                  

@posts.route("/post/<int:post_id>/comment", methods=['GET', 'POST'])
@login_required
def commenter(content, post_id):
    post=Post.query.get_or_404(post_id)
    author=post.author
    comment=Comment(content=content, author=current_user, post_id=post_id )
    db.session.add(comment)
    db.session.commit()
    post.nbrcomments+=1
    if not current_user==author:
        #notif=Notif.query.filter_by(title='PostCommented').first()
        #author.notifs.append(notif)
       # author.getnot+=1
        db.session.commit()
    flash('Your comment has been added', 'success')
    return redirect (url_for('posts.post', post_id=post.id))
   

@posts.route("/post/<int:post_id>/<int:comment_id>/reply", methods=['GET', 'POST'])
@login_required
def reply(comment_id, post_id):
    comment=Comment.query.get_or_404(comment_id)
    post=Post.query.get_or_404(post_id)
    
    content=request.form.get('reply')
    if len(content)>0:
        reply=Reply(content=content, author=current_user, comment_id=comment.id)
        db.session.add(reply)
        db.session.commit()
        comment.rep=1
        flash('Your reply has been added', 'success')
        return redirect (url_for('posts.post', post_id=post.id))
    else:    
        flash('The reply has no content ', 'danger')
    return redirect (url_for('main.home'))


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))                           


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    if request.method=='POST':
   
        content=request.form.get('postcontent')
        if len(content)<0:
            flash('A post must have at least 300 words', 'danger')
            return redirect(url_for('main.home'))

    
        post.content=content
        db.session.commit()
        flash('Your post has been updated', 'success')
        return redirect(url_for('main.home'))
    else:
        flash('Post not updated', 'danger')

           
    return render_template('postupdate.html', post=post)



@posts.route("/post/<int:post_id>/updated", methods=['GET', 'POST'])
@login_required
def updatedpost(post_id):
    post = Post.query.get_or_404(post_id)
    if request.method=='POST':
   
        content=request.form.get('postcontent')
        if len(content)<0:
            flash('A post must have at least 300 words', 'danger')
            return redirect(url_for('main.home'))

    
        post.content=content
        db.session.commit()
        flash('Your post has been updated', 'success')
        return redirect(url_for('main.home'))
    else:
        flash('Post not updated', 'danger')

        return redirect(url_for('main.home'))
   

@posts.route('/like/<int:post_id>/<action>')
@login_required
def like_action(post_id, action):
    post = Post.query.filter_by(id=post_id).first_or_404()
    if action == 'like':
        if current_user.has_liked_post(post):
            current_user.unlike_post(post)
            post.like-=1
            db.session.commit()
        else:
            current_user.like_post(post)
            post.like+=1
            db.session.commit()   
        return redirect(url_for('posts.post', post_id=post.id))         
       

@posts.route('/home/post/<int:tag_id>/')
def tag_posts(tag_id):
    tag=Tag.query.filter_by(id=tag_id).first_or_404()
    page = request.args.get('page', 1, type=int)
    posts=tag.posts.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('tag_posts.html', posts=posts)


@posts.route('/home/<string:category>')
def posts_bygenre(category):
    form=SearchForm()
    page = request.args.get('page', 1, type=int)
    try:
        genre=Genre.query.filter_by(title=category).first()
        posts=Post.query.filter_by(category=genre.title)\
            .order_by(Post.date_posted.desc())\
            .paginate(page=page, per_page=5)
    except:
        return redirect(url_for('main.home'))
    genres=Genre.query.all()
    return render_template('posts_bygenre.html', genre=genre, posts=posts, genres=genres, form=form)    

        

myapp/templates/essai.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Summernote</title>
  <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">
  <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script> 
  <script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"></script> 
  <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css" rel="stylesheet">
  <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.js"></script>
</head>
<body>
  <div id="summernote"><p>Hello Summernote</p></div>
  <script>
    $(document).ready(function() {
        $('#summernote').summernote();
    });
  </script>
</body>
</html>


<div class="form-group">
                
        {{ form.content.label(class="form-control-label") }}
        {% if form.content.errors %}
            {{ form.content(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% else %}
            {{ form.content(class="form-control form-control-lg") }}
        {% endif %}
    
    </div>

myapp/templates/file.html
{% extends "layout.html" %}
{% block content%}
{{ share.load() }}

<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + file.uploader.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" >{{ file.uploader.username }}</a>
        <small class="text-muted">{{ file.date_posted.strftime('%Y-%m-%d') }}</small>
        <small class="text-muted">{{ file.uploader.location }}</small>
        
      </div>
        <h2 class="article-title">{{ file.title | safe }}</h2>
        <h8>{{file.auteur}}</h8>
        <div class="imagecover">
          <img class="cover" src="{{url_for('files.serve_image', img_id=file.img_id)}}">
        </div>
        <p class="article-content">{{ file.description | safe }}</p>
        
    </div>
    
</article>
  
  <a href="{{url_for('files.download', file_id=file_id)}}">
   <button class="btn"><i class="fa fa-download"></i> Download {{ file_size }} MB </button>
  </a>
  


  {{ share.create(title='Share with: ') }}  

{% endblock content %}

myapp/templates/files.html
{% extends "layout.html" %}
{% block content %}



<article class="media content-section">
  
  <div class="media-body">
   
    <div class="article-metadata">
      
      <div> 
        {% for genre in genres %}
        <a href="{{url_for('files.files_bygenre', category=genre.title)}}"><span class="badge badge-primary">{{ genre.title }} </span></a>
        {% endfor %}
      </div>
    </div>
    
  </div>
</article>

<!--
    {% for file in files.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + file.uploader.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
             <a class="mr-2" >{{ file.uploader.username }}</a>
              <small class="text-muted">{{ file.date_posted.strftime('%Y-%m-%d') }}</small>
              <small class="text-muted">{{ file.uploader.location }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('files.file', file_id=file.id) }}">{{ file.title }}</a></h2>
            
            <p class="article-content">{{ file.description[:30]|safe}} <a href="{{url_for('files.file', file_id=file.id)}}">Read more...</a></p>
          </div>
        </article>
    {% endfor %}
-->

    


    <div class="container">
      
        <div class="row">
          {% for file in files.items %}
            <div class="col-sm-4 py-2">
              <div class="card h-100 text-white bg-danger">
                
                  <div class="card-body">
                    
                      <a href="{{ url_for('files.file', file_id=file.id) }}" class="article-title">
                        <h6 class="card-title">{{file.title}}</h6>
                      </a>                      
                      
                      <div class="imagecover">
                        <img class="cover" src="{{url_for('files.serve_image', img_id=file.img_id)}}">
                      </div>
                      <h8>{{file.auteur}}</h8>
                     
                  </div>
                
              </div>
            </div>
          
          {% endfor %}   
        </div>
    </div>  
    {% for page_num in files.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if files.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('files.allfiles', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('files.allfiles', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}


{% endblock content %}

myapp/templates/files_bygenre.html
{% extends "layout.html" %}

 
 
{% block content %}

     
<form method="POST" action="">
  {{ form.hidden_tag() }}
  <fieldset class="form-group">
      
      <div class="form-group">
          
          {% if form.search.errors %}
              {{ form.search(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                  {% for error in form.search.errors %}
                      <span>{{ error }}</span>
                  {% endfor %}
              </div>
          {% else %}
              {{ form.search(class="form-control form-control-lg") }}
          {% endif %}
      </div>
  </fieldset>
  <div class="form-group">
    {{ form.submit(class="btn btn-outline-info") }}
    
  </div>  
</form>  


<article class="media content-section">
  
  <div class="media-body">
   
    <div class="article-metadata">
      
      <div> <!--POur les tags-->
        {% for genre in genres %}
          <a href="{{url_for('files.files_bygenre', category=genre.title)}}"><span class="badge badge-primary">{{ genre.title }}</span> </a>
        {% endfor %}  
      </div>
      <h1>{{genre.title}}</h1>  
    </div>
    
  </div>
</article>


<!--
{% for file in files.items %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + file.uploader.image_file) }}">
      <div class="media-body">
        <div class="article-metadata">
         <a class="mr-2" >{{ file.uploader.username }}</a>
          <small class="text-muted">{{ file.date_posted.strftime('%Y-%m-%d') }}</small>
          <small class="text-muted">{{ file.uploader.location }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('files.file', file_id=file.id) }}">{{ file.title }}</a></h2>
        
        <p class="article-content">{{ file.description[:30]|safe}} <a href="{{url_for('files.file', file_id=file.id)}}">Read more...</a></p>
      </div>
    </article>
{% endfor %}
-->


    <div class="container">
      
        <div class="row">
          {% for file in files.items %}
          <div class="col-sm-4 py-2">
              <div class="card h-100 text-white bg-danger">
                  <div class="card-body">
                    <a href="{{ url_for('files.file', file_id=file.id) }}" class="article-title">
                      <h3 class="card-title">{{file.title}}</h3>
                    </a>  
                      <div class="imagecover">
                        <img class="cover" src="{{url_for('files.serve_image', img_id=file.img_id)}}">
                      </div>
                      <p class="card-text">{{file.description[:25]}}</p>
                      <a href="#" class="btn btn-outline-light">Outline</a>
                  </div>
              </div>
          </div>
          {% endfor %}   
        </div>
    </div>  
    {% for page_num in files.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if files.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('files.files_bygenre', category=genre.title, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('files.files_bygenre', category=genre.title, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}    
  
{% endblock content %}

myapp/templates/postcomments.html
{% extends "layout.html" %}
{% block content %}


<article class="media content-section">
  <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
      <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
      <small class="text-muted">{{ post.author.location }}</small>
      {% if post.author == current_user %}
        <div>
          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
          <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
        </div>
      {% endif %}
    </div>
    <h2 class="article-title">{{ post.title | safe }}</h2>
    <p class="article-content">{{ post.content | safe }}</p>
  </div>
</article>


<a href="{{url_for('posts.post', post_id=post.id)}}">Comments section</a>


{% for comment in comments.items %}
<article class="media content-section">
  <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + comment.author.image_file) }}">
  <div class="media-body">
    <div class="article-metadata">
        <small class="text-muted">{{ comment.author.username }}</small>
      <small class="text-muted">{{ comment.date_posted.strftime('%Y-%m-%d') }}</small>
      <small class="text-muted">{{ comment.author.location }}</small>
      {% if comment.receveur %}
        <small class="text-muted">reply to {{ comment.receveur }}</small>
      {% endif %}
    </div>
    
    <p class="article-content">{{ comment.content | safe }}</p>
<!--replies -->
    <form method="POST", action="">
  
    
      <div class="form-group">
        {{ form.content.label(class="form-control-label") }}
        {% if form.content.errors %}
          {{ form.content(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
              {% for error in form.content.errors %}
                <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.content(class="form-control form-control-lg") }}
       
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
    </form>

  </div>
</article>
{% endfor %}
  


{% endblock content %} 

myapp/templates/tag_posts.html
{% extends "layout.html" %}

{% block content %}
{% for post in posts.items %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        <small class="text-muted">{{ post.author.location }}</small>
      </div>
      <div class="article-metadata">
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content[:220]|safe}} <a href="{{url_for('posts.post', post_id=post.id)}}">Read more...</a></p>
        <div> <!--POur les tags-->
          {% for tags in post.tags %}
            <a href="{{ url_for('posts.tag_posts', tag_id=tags.id) }}"><span class="badge badge-primary">{{ tags.title }}</span></a>
            
          {% endfor %}
        </div>
      </div>
      
    </div>
  </article>
{% endfor %}

{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
        {% if posts.page == page_num %}
            <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
    {% else %}
        ...
    {% endif %}
{% endfor %}


{% endblock content %}